name: Daniel APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk wget python3-pip
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Bootstrap Buildozer (to generate .buildozer directory)
      run: |
        buildozer android debug || true

    - name: Manually install Android cmdline-tools
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools latest

    - name: Accept Android licenses and install build tools
      run: |
        export SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        yes | $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT --licenses
        yes | $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT "platform-tools" "build-tools;33.0.0" "platforms;android-33"

    - name: Build final APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorld-APK
        path: bin/*.apk
