name: Daniel test build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git openjdk-17-jdk python3-pip zip unzip
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Trigger initial environment download
      run: |
        buildozer android debug || true

    - name: List contents to locate sdkmanager
      run: |
        find ~/.buildozer/android/platform/android-sdk -type f -name sdkmanager

    - name: Accept Android SDK Licenses (robust)
      run: |
        yes | $(find ~/.buildozer/android/platform/android-sdk -type f -name sdkmanager) --licenses

    - name: Final Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorld-APK
        path: bin/*.apk
